### ISSUE TITLE
self-hosted deployment with nginx

### ISSUE THREAD

**Issue by montarion** [BrunoBernardino/budgetzen-web#4]
Hi!

This looks great, I just can't get it to run.. 

I do a ``make start``, which launches deno and that works. 

Then a simple reverse proxy in nginx:

```
proxy_pass $upstream;
proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_cache_bypass $http_upgrade;
```
Leads to a bunch of mimetype browser console errors like:

``The resource from “https://budget.example.com/public/scss/style.scss” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).``

Happens for ``css``, ``scss``, ``ts``, and ``js``.

Fixing that by doing 

```
location ~ \.css {
        add_header  Content-Type    text/css;
    }
    location ~ \.js {
        add_header  Content-Type    application/javascript;
    }
    location ~ \.scss {
        add_header  Content-Type    text/css;
    }
    location ~ \.ts {
        add_header  Content-Type    application/javascript;
    }
```

Gets rid of those errors, leaving only:

``Uncaught SyntaxError: unexpected token: 'as' index.ts:26:58`` for /public/ts/index.ts.

AFAIK typescript shouldn't be sent to a browser, so I'm not sure why that file is requested.

Also.. the deployment instructions in the README file could use some elaboration. I feel like I'm missing a lot of info, and I'd love to use your product.

**Comment by BrunoBernardino** [comment]
@montarion thanks for reporting this! All files should be proxied through Deno. It will transpile SCSS and TS on the fly, for example (that's why it can be "requested"). For JS/CSS/images I suppose you can proxy without a problem as there's no interesting manipulation happening for those.

Not sure what those errors are without more context (were they being thrown by the server or the browser? Was it because the certificate validation failed, or something in the response? Any error in the server?). I personally use `caddy` for local development and in production without any of those problems. The file is really just a simple proxy:

```Caddyfile
budgetzen.example.com {
	tls email@example.com
	encode gzip zstd

	reverse_proxy localhost:3000 {
		header_up Host {host}
		header_up X-Real-IP {remote}
		header_up X-Forwarded-Host {upstream_hostport}
	}
}
```

With a custom `docker-compose.yml` file:
```docker-compose
version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - 127.0.0.1:3000:8000
```

And that's it.

Let me know if that helps, or if you're still running into any issues!

**Comment by montarion** [comment]
Turns out the rest of my nginx config was overcomplicated from trying to fix other errors (like the mimetype errors I got in my browser when serving files directly with nginx). In the end, my config looks like this:

```
set $upstream http://127.0.0.1:10003;

location / {
    proxy_pass $upstream;
}
````

**Comment by BrunoBernardino** [comment]
Thanks for sharing your solution!

**Comment by montarion** [comment]
I'm not quite sure how to do pull requests, so instead I forked your repo here: https://github.com/montarion/budgetzen-web-localhosted.

I've made changes to `pages/api/session.ts`, `lib/data-utils,ts`, README.md, and added an examples folder.

Changes:
session.ts: Disabled mail sending, since it crashes when brave isn't configured. Instead printed the verification code to the terminal.
data-utils.ts: Set newly created user status to active instead of trial, and changed the expiry date to 2100-01-01.
README.md: elaborated on the deployment instructions.

Please feel free to take whatever you want from my changes.

Also, if this infringes on your ability to make money through your subscription platform, please tell me if there's anything you'd like me to change or remove outright.

Again, thanks for your efforts!

**Comment by BrunoBernardino** [comment]
Thanks @montarion you're welcome to fork and I have no issues with it! If you start selling that, you just need to make sure the source code keeps being open and under a similar license (if you don't want that, then we'd just need to discuss a new license for you)!

Here's what I'll do to close this issue and make it a bit easier to self-host on a local machine:

- Add a new `IS_UNSAFE_SELF_HOSTED` env var that when is set to a non-empty string, it'll automatically create accounts in `active` mode, with a subscription ending in 50 years, and log verification codes in the console _instead_ of trying to send an email.

The other points about the self-hosting setup are very use-case specific and I already provide instructions with `caddy` which handles SSL and is, in my opinion, easier to setup and maintain than nginx.
